{% set name = "xilinx-runtime" %}
{% set version = "2.13.466" %}
{% set quarter = "202210" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/Xilinx/XRT/archive/refs/tags/{{ quarter }}.{{ version }}.tar.gz
  sha256: d73d8366f6f6d66bfdcb67e72135f559a4d95644c5416c27dea79c235953fd20
  patches:
    - latest.patch
    - conda.patch

build:
  number: 0
  skip: true  # [win]
  skip: true  # [osx]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - pkg-config
    - git

  host:
    - python
    - pybind11
    - boost
    - protobuf
    - rapidjson
    - libuuid
    - libdrm
    - clhpp
    - libcurl

  run:
    - python
    - boost
    - boost-cpp
    - openssl
    - libprotobuf
    - rapidjson
    - libuuid
    - libdrm
    - clhpp
    - libcurl

test:
  commands:
    - xbutil --help

about:
  home: https://www.origin.xilinx.com/products/design-tools/vitis/xrt.html
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Xilinx Runtime for Heterogenous Acceleration
  description: Xilinx Runtime for Heterogenous Acceleration
  dev_url: https://github.com/Xilinx/XRT
  doc_url: https://xilinx.github.io/XRT

extra:
  recipe-maintainers:
    - bryanloz-xilinx
